export const apiErrorMessageMap: Record<string, string> = {
  COMMON_INVALID_REQUEST: "입력한 내용을 다시 확인해 주세요.",
  COMMON_INTERNAL_SERVER_ERROR: "서버에서 요청을 처리하지 못했습니다.",
  AUTHENTICATION_REQUIRED: "로그인이 필요하거나 로그인 정보가 만료되었습니다.",
  ACCESS_DENIED: "이 기능을 사용할 권한이 없습니다.",
  LOGIN_FAILED: "아이디 또는 비밀번호가 올바르지 않습니다.",
  ACCOUNT_NOT_ACTIVE: "현재 사용할 수 없는 계정입니다.",
  LOGIN_ID_ALREADY_EXISTS: "이미 사용 중인 아이디입니다.",
  EMAIL_ALREADY_EXISTS: "이미 가입된 이메일입니다.",
  POLL_NOT_FOUND: "투표를 찾을 수 없습니다.",
  POLL_CLOSED: "종료된 투표에는 참여할 수 없습니다.",
  POLL_OPTION_INVALID: "해당 투표의 선택지가 아닙니다.",
  POLL_ALREADY_VOTED: "이미 이 투표에 참여했습니다.",
  POLL_SELECTION_COUNT_INVALID: "선택할 수 있는 문항 수를 확인해 주세요.",
  POLL_END_TIME_INVALID: "투표 종료 시간은 현재부터 60분 이내로 설정해 주세요.",
  POLL_EDIT_NOT_ALLOWED: "참여자가 있는 투표의 문항은 변경할 수 없습니다.",
  POLL_STATUS_INVALID: "현재 투표 상태에서는 요청한 상태로 변경할 수 없습니다.",
  DOCUMENT_NOT_FOUND: "삭제되었거나 존재하지 않는 문서입니다.",
  DOCUMENT_EDIT_FORBIDDEN: "이 문서를 수정할 권한이 없습니다.",
  DOCUMENT_VERSION_CONFLICT: "다른 사용자가 먼저 수정했습니다. 최신 내용을 확인해 주세요.",
  FILE_ACCESS_FORBIDDEN: "다른 사용자가 올린 파일은 현재 문서에 사용할 수 없습니다.",
  FILE_NOT_IMAGE: "대표 이미지에는 이미지 파일만 사용할 수 있습니다.",
  FILE_NOT_FOUND: "파일을 찾을 수 없습니다.",
  FILE_EXTENSION_NOT_ALLOWED: "업로드할 수 없는 파일 형식입니다.",
  FILE_SIZE_EXCEEDED: "업로드 가능한 파일 크기를 초과했습니다.",
  NETWORK_CONNECTION_FAILED: "백엔드 서버에 연결할 수 없습니다.",
};
